### PR TITLE
[WIP] Cleaning unused tokens from APNS and GCM

### PR DESCRIPTION
**Pull request by Raphcal**

### CODE REVIEW

**Comment by dcai** [comment]
@Raphcal Thanks for contributing!

**Comment by Phoenix09** [comment]
Clearly this wasn't tested in any way before being merged:
```
$ ./airnotifier.py
Traceback (most recent call last):
  File "./airnotifier.py", line 38, in <module>
    from pushservices.gcm import GCMClient
  File "/opt/airnotifier/pushservices/gcm.py", line 53, in <module>
    class GCMClient(PushService):
  File "/opt/airnotifier/pushservices/gcm.py", line 99, in GCMClient
    def send(self, regids, data=None, collapse_key=None, ttl=None, retries=5, appdb=appdb):
NameError: name 'appdb' is not defined
```

What's the point in Travis running `make test` when all that does is run `true`?
It doesn't even attempt to run airnotifier, making using Travis completely pointless.

**Comment by Raphcal** [comment]
@Phoenix09 Really sorry for this, the branch was still work in progress when it was merged. I'm fixing this ASAP

**Comment by dcai** [comment]
@Phoenix09 my apologies, I shouldn't merge it before merging it, I will find some time to implement proper testing for airnotifier.

**Pull request merged**
